Добавлен проект
taratuhin/QmlMovement pull request #1
Opened 2024-04-02 06:31 UTC by taratuhin

Добавлен файл CHANGELOG.md

2024-04-02 12:56 UTC, Toxin65 commented on Main.qml
> +                button.show()
Интервал таймера создания нужно менять при каждой сработке случайно, см. ТЗ.

2024-04-02 12:57 UTC, Toxin65 commented on button.qml
> +        x: Math.random() * 280// + width
Надо у родителя брать. Кажется `parent.width` должен работать.
И делать это надо не биндингом тогда уж.

2024-04-02 12:59 UTC, Toxin65 commented on button.qml
> +            onEntered: hovered = true
А кто будет обратно в false возвращать?
Я думаю `MouseArea` излишне.

2024-04-02 13:00 UTC, Toxin65 commented on button.qml
> +                mainWindow:color = "Red"
Обращение через двоеточие? Это интересно, никогда такого не видел.

2024-04-02 13:01 UTC, Toxin65 requested changes
Есть несоответствие ТЗ.

2024-04-03 17:09 UTC, Toxin65 commented on Main.qml
> +                button.show
А скобочки не нужны разве?

2024-04-03 17:10 UTC, Toxin65 commented on Main.qml
> +                var component = Qt.createComponent("button.qml")
В условии не было, но зачем было разбивать на два QML непонятно.

2024-04-03 17:12 UTC, Toxin65 commented on button.qml
> +                btn.y += 0.25
Ого, а почему скорости у всех одинаковые, по ТЗ скорости падения разные от кнопки к кнопке.

2024-04-03 17:12 UTC, Toxin65 commented on button.qml
> +Item {
Этот `Item` у вас вместо главного окна, по сути. Зачем?

2024-04-03 17:13 UTC, Toxin65 commented on button.qml
> +    height: mainWindow.height
Ой как некрасиво! Куча `Item` ов друг на друге будет, нееее, так совсем нехорошо. Вертайте в один файл всё и через `Component`

2024-04-03 17:14 UTC, Toxin65 requested changes
Похоже опять есть нарушение ТЗ.

2024-04-03 18:04 UTC, taratuhin commented on Main.qml
> +                button.show
Если поставить скобочки приложение запускается, но в консоль периодически вылазит сообщение:
TypeError: Property 'show' of object QQuickItem(0x5baed0) is not a function

2024-04-03 19:05 UTC, Toxin65 commented on Main.qml
> +                button.show
Значит что-то не так! Это выражение пустое, оно ни к чему не обязывает вообще.

2024-04-03 19:20 UTC, taratuhin commented on button.qml
> +                btn.y += 0.25
Скорость у всех разная. Для каждой кнопки создается свой таймер с разным временем срабатыванием, а это приращение перемещения.

2024-04-03 19:26 UTC, Toxin65 commented on button.qml
> +                btn.y += 0.25
Это не очень хороший подход. Но имеет право на жизнь. Хотя я игрался и индивидуальной скоростью и таймером.
Лучший вариант, кмк, который предложили в этом году, общий таймер перемещения для всех, а скорости у всех свои.

2024-04-03 19:43 UTC, Toxin65 commented on Main.qml
> +                var component = Qt.createQmlObject('
Да что же ты делаешь!!!
Вынеси в `Component` уже!!!

2024-04-06 01:38 UTC, taratuhin commented on button.qml
> +                btn.y += 0.25
Пока не понимаю как событие срабатывания одного таймера связать со всеми динамически созданными объектами, чтобы у каждого объекта в Component можно было увеличить координату `y` на случайное число для каждого объекта и при этом чтоб объекты двигались плавно.

2024-04-08 09:19 UTC, Toxin65 commented on Main.qml
> +    Column {
А зачем он нужен?

2024-04-08 09:20 UTC, Toxin65 commented on Main.qml
> +            id: m_timer
В QML нет таких правил именования, как в плюсах.

2024-04-08 09:36 UTC, Toxin65 commented on Main.qml
> +            x: Math.random() * (mainWindow.width - btn.width)
Этот биндинг, думаю. плохо себя ведёт до разрушения. Я бы не стал делать биндинги вообще!

2024-04-08 09:37 UTC, Toxin65 commented on Main.qml
> +            property double dy: Math.random()
Тут ноль возможен...
Да и диапазон не определён.

2024-04-08 09:38 UTC, Toxin65 commented on Main.qml
> +                    btn.y += dy
Дык запаковать тернарником в одну строку, чё размазывать...

2024-04-08 09:39 UTC, Toxin65 requested changes
В целом неплохо, но есть огрехи, которые надо исправить.

2024-04-08 13:57 UTC, Toxin65 approved these changes

2024-04-09 09:17 UTC, Toxin65 commented on Main.qml
> +            btnTimer.signalBtnTimer()
В качестве примера, конечно неплохо. Но у таймера и так есть сигнал `triggered`, на который и подписан этот обработчик, который испускает уже другой сигнал. Смысла в промежуточном сигнале нет.

2024-04-09 09:18 UTC, Toxin65 commented on Main.qml
> +            Connections {
Да, это подходящий способ. Можно ещё динамически.

2024-04-10 02:02 UTC, taratuhin commented on Main.qml
> +            btnTimer.signalBtnTimer()
Если переделываю на `triggered` вылетает такая ошибка: `QQmlApplicationEngine failed to load component
qrc:/qt/qml/QmlMovement/Main.qml:16:9: Cannot assign to non-existent property "triggered"` Пока не понимаю что происходит.

2024-04-10 07:41 UTC, Toxin65 commented on Main.qml
> +            btnTimer.signalBtnTimer()
Вы не поняли меня, видимо.

2024-04-10 07:42 UTC, Toxin65 commented on Main.qml
> +                function onSignalBtnTimer() {
Вот эта функция `onTriggered` без левого сигнала.

2024-04-13 18:07 UTC, merged